# Generated by Django 4.2.3 on 2023-11-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='название')),
                ('description', models.CharField(max_length=50, verbose_name='описание')),
                ('inform', models.TextField(max_length=1000, verbose_name='описание')),
                ('typeData', models.CharField(max_length=50, verbose_name='тип товара')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата публикации')),
                ('cost', models.FloatField(verbose_name='цена')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('tov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.thing')),
            ],
        ),
    ]
