# Generated by Django 4.2.3 on 2023-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='inform',
            field=models.TextField(max_length=2000, verbose_name='описание'),
        ),
    ]
